<!DOCTYPE html>
<html lang="pt-br" style="margin-top:0px !important;">
	<head>
		<link rel="icon" href="<?= IMG ?>/resouces/assets/images/default/favicon.ico" type="image/x-icon"/>
		<?php  include_once "include/head.phtml"; ?>
	</head>	

    <body> 
		<?php 

		    if(isset($page)){
		        include_once $page.".phtml";
		    }

		?>

		<?php  include_once "include/footer.phtml"; ?>
		
		<!-- FONT-->	
		<link href="https://fonts.googleapis.com/css?family=Exo+2:300,400,700" rel=stylesheet>
		
	</body>
</html>
