<!DOCTYPE html>
<html lang="pt-br" style="margin-top:0px !important;">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Dashboard | Glawiki</title>
		<link rel="icon" href="<?= IMG ?>/resouces/assets/images/default/favicon.ico" type="image/x-icon"/>

		<!-- Font Awesome -->
		<link rel="stylesheet" href="<?= PATH ?>/resouces/assets/css/vendor/fontawesome-free/css/all.min.css">
		<!-- overlayScrollbars -->
		<link rel="stylesheet" href="<?= PATH ?>/resouces/assets/css/vendor/overlayScrollbars/OverlayScrollbars.min.css">
		<!-- Ionicons -->
		<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<!-- icheck bootstrap -->
		<link rel="stylesheet" href="<?= PATH ?>/resouces/assets/css/vendor/icheck-bootstrap/icheck-bootstrap.min.css">
		<!-- tagsinput -->
		<link rel="stylesheet" href="<?= PATH ?>/resouces/assets/css/vendor/tagsinput.css" rel="stylesheet" type="text/css">
		<!-- Theme style -->
		<link rel="stylesheet" href="<?= PATH ?>/resouces/assets/css/vendor/adminlte.min.css">
		<!-- CKeditor -->
		<script src="<?= PATH ?>/resouces/assets/js/vendor/ckeditor/ckeditor.js"></script>
		<!-- Google Font: Source Sans Pro -->
		<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
	</head>	

		<?php 
	
		    if(isset($page)){
		        include_once $page.".phtml";
		    }

		?>

	</body>
</html>
