<?php require 'shared/feedback.php'; ?>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">

        <?php include_once "include/navbar.phtml";  ?>

        <?php include_once "include/sidebar.phtml";  ?>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper mb-0">

            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                <div class="row mb-2">
                    <!-- Feedback de Erros e/ou Aprovações -->
                    <div class="col-sm-12">
                        <?= feedback($status, $feedback); ?>
                    </div><!-- /.col -->

                    <div class="col-sm-6"> <h1 class="m-0 text-dark">Dashboard</h1> </div><!-- /.col -->

                    <div class="col-sm-6"> <ol class="breadcrumb float-sm-right"> </ol> </div><!-- /.col -->
                </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">

                        <!-- Box Evento -->
                        <!--div class="col-12 col-sm-6 col-md-3">
                            <div class="info-box">
                                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-star"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">Eventos</span>
                                    <span class="info-box-number">
                                        <a href="<?php PATH ?>/admin/eventos"> <i>Cadastro</i>  </a> /
                                        <a href="<?php PATH ?>/admin/eventos/list"> <i> Atualização</i>  </a> 
                                    </span>
                                </div>
                            </div>
                        </div-->

                        <!-- Box Torneio -->
                        <!--div class="col-12 col-sm-6 col-md-3">
                            <div class="info-box">
                                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-trophy"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">Vencedores do Torneio</span>
                                    <span class="info-box-number">
                                        <a href="<?php PATH ?>/creator/tournament/form"> <i>Cadastro</i>  </a> /
                                        <a href="<?php PATH ?>/creator/tournament/list"> <i> Atualização</i>  </a> 
                                    </span>
                                </div>
                            </div>
                        </div-->

                        <!-- Box ChangLog -->
                        <!--div class="col-12 col-sm-6 col-md-3">
                            <div class="info-box">
                                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-clipboard-list"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">Change Log</span>
                                    <span class="info-box-number">
                                        <a href="<?php PATH ?>/creator/changelog/form"> <i>Cadastro</i>  </a> /
                                        <a href="<?php PATH ?>/creator/changelog/list"> <i> Atualização</i>  </a> 
                                    </span>
                                </div>
                            </div>
                        </div-->

                        <!-- Box ChangBuffNerf -->
                        <!--div class="col-12 col-sm-6 col-md-3">
                            <div class="info-box">
                                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-clipboard-list"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">Buff e Nerf Personagens</span>
                                    <span class="info-box-number">
                                        <a href="<?php PATH ?>/creator/balancing/form"> <i>Cadastro</i>  </a> /
                                        <a href="<?php PATH ?>/creator/balancing/list"> <i> Atualização</i>  </a> 
                                    </span>
                                </div>
                            </div>
                        </div-->

                    </div>
                </div><!--/. container-fluid -->
            </section>

        </div>

        <?php include_once "include/footer.phtml";  ?>

    </div>    

    <?php include_once "include/script.phtml";  ?>
    