 <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <!-- Feedback de Erros e/ou Aprovações -->
        <div class="col-sm-12">
            <?= feedback($status, $feedback); ?>
        </div><!-- /.col -->

        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->