 <!-- FONT-->	
 <link href="https://fonts.googleapis.com/css?family=Exo+2:300,400,700" rel=stylesheet>
<!-- jQuery -->
<script src="<?= PATH ?>/resouces/assets/js/vendor/jquery-adminLte/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?= PATH ?>/resouces/assets/js/vendor/bootstrap-adminLte/bootstrap.bundle.min.js"></script> 
<!-- overlayScrollbars -->
<script src="<?= PATH ?>/resouces/assets/js/vendor/overlayScrollbars/jquery.overlayScrollbars.min.js"></script>
<!-- Tagsinput -->
<script src="<?= PATH ?>/resouces/assets/js/vendor/tagsinput.js"></script>
<!-- AdminLTE App -->
<script src="<?= PATH ?>/resouces/assets/js/vendor/adminlte.min.js"></script>