<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="<?= DASHBOARD ?>/" class="brand-link">
        <img src="" alt="" class="brand-image img-circle" style="opacity: .8">
        <span class="brand-text font-weight-light">Glawiki Administrativo</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                
            </div>
            <div class="info">
                <a href="<?= DASHBOARD ?>/" class="d-block"> <?= $_SESSION['name'] ?></a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-header">CHARACTER MANAGER</li>
            
                <!-- PERSONAGENS -->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link"> 
                        <i class="nav-icon fas fa-user"></i>
                        <p> Personagens <i class="fas fa-angle-left right"></i> </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="<?= DASHBOARD ?>/manager/character/form" class="nav-link"> <i class="nav-icon far fa-circle text-info"></i>
                                <p>Adicionar Personagem</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?= DASHBOARD ?>/manager/character/list" class="nav-link"> <i class="far fa-circle nav-icon"></i>
                                <p>Listar Personagens</p>
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>    