<?php require __DIR__ . "/../../shared/feedback.php"; ?>

<style>
    .table td, .table th {
        border-top: 0px;
        vertical-align: baseline;
    }
</style>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">
       
        <?php include_once __DIR__ . "/../../include/navbar.phtml";  ?>

        <?php include_once __DIR__ . "/../../include/sidebar.phtml";  ?>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper mb-0">

            <?php include_once __DIR__ . "/../../include/content-header.phtml";  ?>
           
             <!-- Main content -->
             <section class="content">
                <div class="container-fluid">

                    <div class="row">
                        <div class="col-12 col-sm-6 col-md-12">
                            <!-- general form elements -->
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">LISTA DE PERSONAGENS</h3>
                                </div>
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                    <!-- /.row -->
            
                    <!-- /.row -->
                    <div class="row">
                        <div class="col-12">
                            <div class="card"style="height: 75vh;">
                                <div class="card-header">
                                    <div class="row">
                                        <div class="col-md-12" style="margin-top: 5px;">
                                            <input type="text" name="table_search" class="form-control float-right" id="text-filter-info" placeholder="Search">
                                        </div>
                                    </div>                   
                                </div>

                                <!-- /.card-header -->
                                <div class="card-body table-responsive p-0" style="height: 300px;">
                                    <table class="table table-head-fixed text-nowrap">
                                        <thead>
                                            <tr>
                                                <th>Icon</th>
                                                <th>Nome</th>
                                                <th>Classes</th>
                                                <th>Tier</th>
                                                <th>Skins</th>
                                                <th>Skins</th>
                                                <th>Magias</th>
                                                <th>Magias</th>
                                                <th>Editar</th>
                                                <th>Deletar</th>
                                            </tr>
                                        </thead>
                                        <tbody> 
                                            <?php $dataPos= 0; foreach($characters as $result) : $dataPos++?>
                                            <tr class="tr-info" data-title-<?= $dataPos ?>="<?= $result->nomePersonagem ?>">
                                                <td> <img src="<?= IMG ?>/resouces/assets/images/characters/<?= $result->slugPersonagem?>.png" class="brand-image" style="width: 80px;"> </td>
                                                <td><?= $result->nomePersonagem ?></td>
                                                <td> 
                                                    <img  src="<?= IMG ?>/resouces/assets/images/icons/<?= $result->classe_a?>.png" class="brand-image" style="width: 20px;">

                                                    <?php if ($result->classe_b) : ?>
                                                    <img src="<?= IMG ?>/resouces/assets/images/icons/<?= $result->classe_b?>.png" class="brand-image" style="width: 20px;">
                                                    <?php endif; ?>

                                                    <?php if ($result->classe_c) : ?>        
                                                    <img src="<?= IMG ?>/resouces/assets/images/icons/<?= $result->classe_c?>.png" class="brand-image" style="width: 20px;">
                                                    <?php endif; ?>

                                                    <?php if ($result->classe_d) : ?>
                                                    <img src="<?= IMG ?>/resouces/assets/images/icons/<?= $result->classe_d?>.png" class="brand-image" style="width: 20px;">
                                                    <?php endif; ?>
                                                </td>
                                                <th>
                                                    <?php if($result->tierPersonagem == 1) : ?>
                                                        Diamond
                                                    <?php elseif($result->tierPersonagem == 2) : ?>
                                                        Gold
                                                    <?php elseif($result->tierPersonagem == 3) : ?>
                                                        Silver
                                                    <?php elseif($result->tierPersonagem == 4) : ?>
                                                        Bronze
                                                    <?php endif; ?>
                                                </th>
                                                <td><a href="#" class="btn btn-info"> Adicionar </a></td>
                                                <td><a href="#" class="btn btn-secondary"> Ver Skins </a></td>
                                                <td><a href="#" class="btn btn-success"> Adicionar </a></td>
                                                <td><a href="#" class="btn btn-warning"> Ver Magias </a></td>
                                                <td><a href="<?= DASHBOARD ?>/manager/character/edit/<?= $result->idPersonagem ?>" class="btn btn-primary"> Editar </a></td>
                                                <td><a href="<?= DASHBOARD ?>/manager/character/delete/<?= $result->idPersonagem ?>" class="btn btn-danger"> Deletar </a></td>
                                            </tr>
                                            <?php endforeach;?>
                                        </tbody>
                                    </table>
                                </div><!-- /.card-body -->
                            </div><!-- /.card -->
                        </div>
                    </div> <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section><!-- /.content -->

        </div>
    </div>    
   
    <?php include_once __DIR__ .  "/../../include/footer.phtml";  ?>
    <?php include_once __DIR__ .  "/../../include/script.phtml";  ?>

    <script type="text/javascript">

        // Percorre toda a tabela e oculta todos os personagens que não são bronzes

        function StartFilter() {
            $(document).ready(function(){
                // tier: 4:Bronze, 3:Silver, 2:Gold, 1:Diamond
                var tier = $("#data-info-select").val();
                var dataPos = 0;

                $('.tr-info').each(function () { dataPos++;
                    var dataName = $(this).attr("data-title-"+dataPos).toUpperCase();
                    //var dataTier = $(this).attr("data-tier-"+dataPos);

                    if(dataTier.indexOf(tier) < 0) {
                        $(this).hide();
                    }else {
                        $(this).show();
                    }

                });
            });
        }

        StartFilter();
        

        $(function(){

            // Caso o usuário digite no filtro
            $("#text-filter-info").keyup(function(){
                var textInput = $(this).val().toUpperCase(); // Recebendo valor digitado do input
                var tier = $("#data-info-select").val(); // tier: 4:Bronze, 3:Silver, 2:Gold, 1:Diamond
                var dataPos = 0; // Variavel de incremento para pegar os valores de cada data-title-X especifico.

                $('.tr-info').each(function () { dataPos++;
                    var dataName = $(this).attr("data-title-"+dataPos).toUpperCase();
                    var dataTier = $(this).attr("data-tier-"+dataPos);

                    if( dataName.indexOf(textInput) < 0 ) {
                        $(this).hide();
                    }else {
                        $(this).show();
                    }

                    // Caso não exista Texto no filtro
                    if(textInput == ""){
                        StartFilter();
                    }
                });
            });

            // Filtrando Pela Região
            $('#data-info-select').change(function(event){
                // tier: 4:Bronze, 3:Silver, 2:Gold, 1:Diamond
                var tier = $(this).val();
                var dataPos = 0;

                $('.tr-info').each(function () { dataPos++;
                    var dataTier = $(this).attr("data-tier-"+dataPos);

                    if(dataTier.indexOf(tier) < 0) {
                        $(this).hide();
                    }else {
                        $(this).show();
                    }

                });
            
            });

        });


    </script>

    
