 
        <meta charset="utf-8" />
        <meta name=viewport content="width=device-width, initial-scale=1.0 user-scalable=no">
        <title> <?php  echo "$title - Blog  Wiki do Grand Line Adventures"; ?> </title>
        <meta name="description" content="<?php  echo $description; ?> ">

        <meta property="og:locale" content="pt_BR">
        <meta property="og:type" content="website">
        <meta property="og:url" content="https://wiki.gla.com.br">
        <meta property="og:site_name" content="GlaWiki">
        <meta property="og:title" content="<?php echo $midiaTitle; ?>">
        <meta property="og:description" content="<?php echo $description; ?> ">
		
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:description" content=" <?php  echo $description; ?> ">
        <meta name="twitter:title" content="<?php echo $midiaTitle; ?>">

	<!-- CSS -->
 	<link rel="stylesheet" href="<?= PATH ?>/resouces/assets/css/vendor/container.css">
        <link rel="stylesheet" href="<?= PATH ?>/resouces/assets/css/main.css?<?php echo time() ?>">
   
       
	    

      
   
